[package]
name = "rheo-pdf"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
# Core
rheo-core = { path = "../core", version = "0.2.0" }

# Error handling
thiserror = { workspace = true }

# Logging
tracing = { workspace = true }

# File utilities
tempfile = { workspace = true }
