version = "0.2.1"
content_dir = "content"

[html]

[[html.assets]]
copy = ["rheo-slides/**"]
css_stylesheet = "rheo-slides/index.css"
js_scripts = "rheo-slides/index.js"

[html.spine]
vertebrae = ["*.typ"]

[pdf.spine]
title = "rheo_project"
vertebrae = ["index.typ"]
merge = false

[epub.spine]
title = "rheo_project"
vertebrae = ["index.typ", "about.typ"]
