[package]
name = "rheo-html"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
# Core
rheo-core = { path = "../core", version = "0.2.1" }

# Error handling
thiserror = { workspace = true }

# Logging
tracing = { workspace = true }

# Development server
tokio = { workspace = true }
axum = { workspace = true }
tower = { workspace = true }
tower-http = { workspace = true }
webbrowser = { workspace = true }
tokio-stream = { workspace = true }
mime_guess = { workspace = true }

