[package]
name = "rheo-html"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
# Core
rheo-core = { workspace = true }
toml = { workspace = true }
chrono = { workspace = true }

# Error handling
thiserror = { workspace = true }

# Logging
tracing = { workspace = true }

# Development server
tokio = { workspace = true }
axum = { workspace = true }
tower = { workspace = true }
tower-http = { workspace = true }
webbrowser = { workspace = true }
tokio-stream = { workspace = true }
mime_guess = { workspace = true }
atom_syndication = "0.12.8"

[dev-dependencies]
tempfile = { workspace = true }

