//! Converts Typst HTML output into portable XHTML.

use markup5ever_rcdom::{Handle, NodeData};
use rheo_core::Result;
use rheo_core::util::html::{HtmlDom, SerializeMode, escape_attr, escape_text, is_void_element};
use rheo_core::util::typst_types::EcoString;
use std::{fmt::Write, slice};

/// Metadata about features used by the HTML generated by Typst.
pub struct HtmlInfo {
    /// True if the document uses Javascript in any way.
    pub scripted: bool,

    /// True if the document uses MathML in any way.
    pub mathml: bool,
}

/// Converts an HTML document output by Typst into portable XHTML.
///
/// # Arguments
/// * `html_string` should be generated by Typst.
/// * `heading_ids` is a list of CSS identifiers for all heading elements h2-h6, in the order
///   they appear in the document.
///
/// # Notes
/// - HTML parsing uses the [`html5ever`] crate from Servo. It should be generally accurate, although
///   the devs note it sometimes deviates from the spec.
///   See: https://github.com/servo/html5ever/issues?q=is%3Aopen+is%3Aissue+label%3Aweb-compat
/// - Eventually the XHTML functionality should be removed once it is implemented in Typst.
///   See: https://github.com/typst/typst/issues/6446
pub fn html_to_portable_xhtml(
    html_string: &str,
    heading_ids: &[EcoString],
) -> Result<(String, HtmlInfo)> {
    let dom = HtmlDom::parse(html_string)?;

    struct Walker<'a> {
        buf: String,
        heading_ids: slice::Iter<'a, EcoString>,
        info: HtmlInfo,
    }

    impl Walker<'_> {
        fn walk(&mut self, handle: &Handle) {
            match &handle.data {
                NodeData::Document => {
                    // XHTML needs an `<?xml?>` declaration at the top.
                    self.buf
                        .push_str(r#"<?xml version="1.0" encoding="UTF-8"?>"#);
                    self.buf.push_str("\n<!DOCTYPE html>\n");

                    for child in handle.children.borrow().iter() {
                        self.walk(child);
                    }
                }

                NodeData::Text { contents } => {
                    let text = contents.borrow();
                    self.buf.push_str(&escape_text(&text));
                }

                NodeData::Element { name, attrs, .. } => {
                    write!(self.buf, "<{}", name.local).unwrap();

                    if &name.local == "script" {
                        self.info.scripted = true;
                    }

                    if &name.local == "math" {
                        self.info.mathml = true;
                    }

                    if &name.local == "html" {
                        write!(self.buf, " xmlns=\"http://www.w3.org/1999/xhtml\"").unwrap();
                    }

                    for attr in attrs.borrow().iter() {
                        let escaped_value = escape_attr(&attr.value, &SerializeMode::Xhtml);
                        write!(self.buf, " {}=\"{}\"", attr.name.local, escaped_value).unwrap();
                    }

                    let mut chars = name.local.chars();
                    if let Some(first_char) = chars.next()
                        && first_char == 'h'
                        && let Some(c) = chars.next()
                        && c.is_numeric()
                        && c != '1'
                    {
                        // Internal invariant: heading_ids is populated from the
                        // same Typst document that generated these heading nodes.
                        let id = self.heading_ids.next().expect("missing heading id!");
                        write!(self.buf, " id=\"{id}\"").unwrap();
                    }

                    // Void elements use self-closing syntax in XHTML.
                    if is_void_element(&name.local) {
                        write!(self.buf, "/>").unwrap();
                    } else {
                        write!(self.buf, ">").unwrap();

                        // Wrap the children of the body in an <article>.
                        //
                        // TODO: should this be done within the Typst generator?
                        if &name.local == "body" {
                            self.buf.push_str("<article>");
                        }

                        for child in handle.children.borrow().iter() {
                            self.walk(child);
                        }

                        if &name.local == "body" {
                            self.buf.push_str("</article>");
                        }

                        write!(self.buf, "</{}>", name.local).unwrap();
                    }
                }

                _ => {}
            }
        }
    }

    let mut walker = Walker {
        buf: String::new(),
        heading_ids: heading_ids.iter(),
        info: HtmlInfo {
            scripted: false,
            mathml: false,
        },
    };
    walker.walk(dom.document_root());

    Ok((walker.buf, walker.info))
}

#[test]
fn test_html_to_xhtml() {
    let input = r#"<!DOCTYPE html>
<html>
    <head>
        <meta name="foo" content="bar">
    </head>
    <body>
        <h2>Test</h2>
        <p>Hello
        <p>World
    </body>
</html>"#;

    let expected = r#"<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"><head>
        <meta name="foo" content="bar"/>
    </head>
    <body><article>
        <h2 id="test">Test</h2>
        <p>Hello
        </p><p>World
    
</p></article></body></html>"#;

    let (actual, _) = html_to_portable_xhtml(input, &["test".into()]).unwrap();
    assert_eq!(expected, actual);
}
