//! Converts Typst HTML output into portable XHTML.

use rheo_core::Result;
use rheo_core::html_dom::HtmlDom;

/// Metadata about features used by the HTML generated by Typst.
pub struct HtmlInfo {
    /// True if the document uses Javascript in any way.
    pub scripted: bool,

    /// True if the document uses MathML in any way.
    pub mathml: bool,
}

/// Serializes `dom` as portable XHTML and reports which EPUB manifest
/// properties (`scripted`, `mathml`) its content requires.
///
/// # Notes
/// - Eventually the XHTML functionality should be removed once it is implemented in Typst.
///   See: https://github.com/typst/typst/issues/6446
pub fn html_to_portable_xhtml(dom: &HtmlDom) -> Result<(String, HtmlInfo)> {
    let info = HtmlInfo {
        scripted: dom.find_element("script").is_some(),
        mathml: dom.find_element("math").is_some(),
    };
    Ok((dom.serialize_xhtml()?, info))
}

#[test]
fn test_html_to_xhtml() {
    let input = r#"<!DOCTYPE html>
<html>
    <head>
        <meta name="foo" content="bar">
    </head>
    <body>
        <h2>Test</h2>
        <p>Hello
        <p>World
    </body>
</html>"#;

    let expected = r#"<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"><head>
        <meta name="foo" content="bar"/>
    </head>
    <body><article>
        <h2 id="test">Test</h2>
        <p>Hello
        </p><p>World
    
</p></article></body></html>"#;

    let mut dom = HtmlDom::parse(input).unwrap();
    dom.collect_headings();
    let (actual, _) = html_to_portable_xhtml(&dom).unwrap();
    assert_eq!(expected, actual);
}
