version = "0.2.1"
content_dir = "content"

[html]

[[html.assets]]
copy = ["my-tooltip/**"]
js_scripts = "my-tooltip/index.js"

[[html.assets]]
css_stylesheet = "style.css"

[html.spine]
vertebrae = ["*.typ"]

[pdf.spine]
title = "rheo_project"
vertebrae = ["index.typ"]
merge = false

[epub.spine]
title = "rheo_project"
vertebrae = ["index.typ", "about.typ"]
