version = "0.2.1"
content_dir = "content"

[html]
packages = ["./my-tooltip"]

[html.assets]
css_stylesheet = "style.css"

[html.spine]
vertebrae = ["*.typ"]

[pdf.spine]
title = "rheo_project"
vertebrae = ["index.typ"]
merge = false

[epub.spine]
title = "rheo_project"
vertebrae = ["index.typ", "about.typ"]
